name: Run Plugin Inspection

on:
  workflow_dispatch:

env:
  GH_PERSONAL_TOKEN_IONIC: ${{secrets.GH_PERSONAL_TOKEN_IONIC}}
  GH_PERSONAL_TOKEN: ${{secrets.GH_PERSONAL_TOKEN}}
  NPM_PERSONAL_TOKEN: ${{secrets.NPM_PERSONAL_TOKEN}}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: git config --global user.email "damian@ionic.io"
      - run: git config --global user.name "Damian Tarnawsky"
      - run: npm run build --if-present
      - run: npm run publish --if-present
